/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TabTipInterop */

#ifndef _Included_TabTipInterop
#define _Included_TabTipInterop
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     TabTipInterop
	 * Method:    openTabTip
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_TabTipInterop_openTabTip
	(JNIEnv*, jclass);

	/*
	 * Class:     TabTipInterop
	 * Method:    closeTabTip
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_TabTipInterop_closeTabTip
	(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
